/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyVisitTheDentistRouteImport } from './routes/why-visit-the-dentist'
import { Route as VeneersRouteImport } from './routes/veneers'
import { Route as ToothColouredRestorationRouteImport } from './routes/tooth-coloured-restoration'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TeethWhiteningRouteImport } from './routes/teeth-whitening'
import { Route as SmileMakeoversRouteImport } from './routes/smile-makeovers'
import { Route as RegularDentalCheckupsRouteImport } from './routes/regular-dental-checkups'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PorcelainCrownsRouteImport } from './routes/porcelain-crowns'
import { Route as PainlessWisdomToothExtractionRouteImport } from './routes/painless-wisdom-tooth-extraction'
import { Route as PainlessRootCanalTreatmentRouteImport } from './routes/painless-root-canal-treatment'
import { Route as PainlessExtractionsToothRemovalRouteImport } from './routes/painless-extractions-tooth-removal'
import { Route as LaserDentistryRouteImport } from './routes/laser-dentistry'
import { Route as KidsDentistryRouteImport } from './routes/kids-dentistry'
import { Route as InvisalignTreatmentInDelhiNcrRouteImport } from './routes/invisalign-treatment-in-delhi-ncr'
import { Route as InvisalignClearAlignersTeethStraighteningRouteImport } from './routes/invisalign-clear-aligners-teeth-straightening'
import { Route as InvisalignAlignersPanchsheelParkRouteImport } from './routes/invisalign-aligners-panchsheel-park'
import { Route as InvisalignAlignersGolfCourseRoadRouteImport } from './routes/invisalign-aligners-golf-course-road'
import { Route as InternationalPatientsRouteImport } from './routes/international-patients'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FullMouthDentalImplantTreatmentClinicRouteImport } from './routes/full-mouth-dental-implant-treatment-clinic'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as DenturesRouteImport } from './routes/dentures'
import { Route as DentalVeneersGurgaonRouteImport } from './routes/dental-veneers-gurgaon'
import { Route as DentalVeneersDelhiRouteImport } from './routes/dental-veneers-delhi'
import { Route as DentalTourismRouteImport } from './routes/dental-tourism'
import { Route as DentalRctGurgaonRouteImport } from './routes/dental-rct-gurgaon'
import { Route as DentalRctDelhiRouteImport } from './routes/dental-rct-delhi'
import { Route as DentalImplantsInGurgaonRouteImport } from './routes/dental-implants-in-gurgaon'
import { Route as DentalImplantsDelhiRouteImport } from './routes/dental-implants-delhi'
import { Route as DentalImplantClinicGolfCourseRoadRouteImport } from './routes/dental-implant-clinic-golf-course-road'
import { Route as DentalBridgesRouteImport } from './routes/dental-bridges'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as CareerRouteImport } from './routes/career'
import { Route as BracesRouteImport } from './routes/braces'
import { Route as BestSmileMakeoverClinicRouteImport } from './routes/best-smile-makeover-clinic'
import { Route as BestDentalImplantClinicPanchsheelParkRouteImport } from './routes/best-dental-implant-clinic-panchsheel-park'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogBlog_slugRouteImport } from './routes/blog/$blog_slug'

const WhyVisitTheDentistRoute = WhyVisitTheDentistRouteImport.update({
  id: '/why-visit-the-dentist',
  path: '/why-visit-the-dentist',
  getParentRoute: () => rootRouteImport,
} as any)
const VeneersRoute = VeneersRouteImport.update({
  id: '/veneers',
  path: '/veneers',
  getParentRoute: () => rootRouteImport,
} as any)
const ToothColouredRestorationRoute =
  ToothColouredRestorationRouteImport.update({
    id: '/tooth-coloured-restoration',
    path: '/tooth-coloured-restoration',
    getParentRoute: () => rootRouteImport,
  } as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TeethWhiteningRoute = TeethWhiteningRouteImport.update({
  id: '/teeth-whitening',
  path: '/teeth-whitening',
  getParentRoute: () => rootRouteImport,
} as any)
const SmileMakeoversRoute = SmileMakeoversRouteImport.update({
  id: '/smile-makeovers',
  path: '/smile-makeovers',
  getParentRoute: () => rootRouteImport,
} as any)
const RegularDentalCheckupsRoute = RegularDentalCheckupsRouteImport.update({
  id: '/regular-dental-checkups',
  path: '/regular-dental-checkups',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PorcelainCrownsRoute = PorcelainCrownsRouteImport.update({
  id: '/porcelain-crowns',
  path: '/porcelain-crowns',
  getParentRoute: () => rootRouteImport,
} as any)
const PainlessWisdomToothExtractionRoute =
  PainlessWisdomToothExtractionRouteImport.update({
    id: '/painless-wisdom-tooth-extraction',
    path: '/painless-wisdom-tooth-extraction',
    getParentRoute: () => rootRouteImport,
  } as any)
const PainlessRootCanalTreatmentRoute =
  PainlessRootCanalTreatmentRouteImport.update({
    id: '/painless-root-canal-treatment',
    path: '/painless-root-canal-treatment',
    getParentRoute: () => rootRouteImport,
  } as any)
const PainlessExtractionsToothRemovalRoute =
  PainlessExtractionsToothRemovalRouteImport.update({
    id: '/painless-extractions-tooth-removal',
    path: '/painless-extractions-tooth-removal',
    getParentRoute: () => rootRouteImport,
  } as any)
const LaserDentistryRoute = LaserDentistryRouteImport.update({
  id: '/laser-dentistry',
  path: '/laser-dentistry',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsDentistryRoute = KidsDentistryRouteImport.update({
  id: '/kids-dentistry',
  path: '/kids-dentistry',
  getParentRoute: () => rootRouteImport,
} as any)
const InvisalignTreatmentInDelhiNcrRoute =
  InvisalignTreatmentInDelhiNcrRouteImport.update({
    id: '/invisalign-treatment-in-delhi-ncr',
    path: '/invisalign-treatment-in-delhi-ncr',
    getParentRoute: () => rootRouteImport,
  } as any)
const InvisalignClearAlignersTeethStraighteningRoute =
  InvisalignClearAlignersTeethStraighteningRouteImport.update({
    id: '/invisalign-clear-aligners-teeth-straightening',
    path: '/invisalign-clear-aligners-teeth-straightening',
    getParentRoute: () => rootRouteImport,
  } as any)
const InvisalignAlignersPanchsheelParkRoute =
  InvisalignAlignersPanchsheelParkRouteImport.update({
    id: '/invisalign-aligners-panchsheel-park',
    path: '/invisalign-aligners-panchsheel-park',
    getParentRoute: () => rootRouteImport,
  } as any)
const InvisalignAlignersGolfCourseRoadRoute =
  InvisalignAlignersGolfCourseRoadRouteImport.update({
    id: '/invisalign-aligners-golf-course-road',
    path: '/invisalign-aligners-golf-course-road',
    getParentRoute: () => rootRouteImport,
  } as any)
const InternationalPatientsRoute = InternationalPatientsRouteImport.update({
  id: '/international-patients',
  path: '/international-patients',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FullMouthDentalImplantTreatmentClinicRoute =
  FullMouthDentalImplantTreatmentClinicRouteImport.update({
    id: '/full-mouth-dental-implant-treatment-clinic',
    path: '/full-mouth-dental-implant-treatment-clinic',
    getParentRoute: () => rootRouteImport,
  } as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const DenturesRoute = DenturesRouteImport.update({
  id: '/dentures',
  path: '/dentures',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalVeneersGurgaonRoute = DentalVeneersGurgaonRouteImport.update({
  id: '/dental-veneers-gurgaon',
  path: '/dental-veneers-gurgaon',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalVeneersDelhiRoute = DentalVeneersDelhiRouteImport.update({
  id: '/dental-veneers-delhi',
  path: '/dental-veneers-delhi',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalTourismRoute = DentalTourismRouteImport.update({
  id: '/dental-tourism',
  path: '/dental-tourism',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalRctGurgaonRoute = DentalRctGurgaonRouteImport.update({
  id: '/dental-rct-gurgaon',
  path: '/dental-rct-gurgaon',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalRctDelhiRoute = DentalRctDelhiRouteImport.update({
  id: '/dental-rct-delhi',
  path: '/dental-rct-delhi',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalImplantsInGurgaonRoute = DentalImplantsInGurgaonRouteImport.update({
  id: '/dental-implants-in-gurgaon',
  path: '/dental-implants-in-gurgaon',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalImplantsDelhiRoute = DentalImplantsDelhiRouteImport.update({
  id: '/dental-implants-delhi',
  path: '/dental-implants-delhi',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalImplantClinicGolfCourseRoadRoute =
  DentalImplantClinicGolfCourseRoadRouteImport.update({
    id: '/dental-implant-clinic-golf-course-road',
    path: '/dental-implant-clinic-golf-course-road',
    getParentRoute: () => rootRouteImport,
  } as any)
const DentalBridgesRoute = DentalBridgesRouteImport.update({
  id: '/dental-bridges',
  path: '/dental-bridges',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const BracesRoute = BracesRouteImport.update({
  id: '/braces',
  path: '/braces',
  getParentRoute: () => rootRouteImport,
} as any)
const BestSmileMakeoverClinicRoute = BestSmileMakeoverClinicRouteImport.update({
  id: '/best-smile-makeover-clinic',
  path: '/best-smile-makeover-clinic',
  getParentRoute: () => rootRouteImport,
} as any)
const BestDentalImplantClinicPanchsheelParkRoute =
  BestDentalImplantClinicPanchsheelParkRouteImport.update({
    id: '/best-dental-implant-clinic-panchsheel-park',
    path: '/best-dental-implant-clinic-panchsheel-park',
    getParentRoute: () => rootRouteImport,
  } as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogBlog_slugRoute = BlogBlog_slugRouteImport.update({
  id: '/blog/$blog_slug',
  path: '/blog/$blog_slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/best-dental-implant-clinic-panchsheel-park': typeof BestDentalImplantClinicPanchsheelParkRoute
  '/best-smile-makeover-clinic': typeof BestSmileMakeoverClinicRoute
  '/braces': typeof BracesRoute
  '/career': typeof CareerRoute
  '/contact-us': typeof ContactUsRoute
  '/dental-bridges': typeof DentalBridgesRoute
  '/dental-implant-clinic-golf-course-road': typeof DentalImplantClinicGolfCourseRoadRoute
  '/dental-implants-delhi': typeof DentalImplantsDelhiRoute
  '/dental-implants-in-gurgaon': typeof DentalImplantsInGurgaonRoute
  '/dental-rct-delhi': typeof DentalRctDelhiRoute
  '/dental-rct-gurgaon': typeof DentalRctGurgaonRoute
  '/dental-tourism': typeof DentalTourismRoute
  '/dental-veneers-delhi': typeof DentalVeneersDelhiRoute
  '/dental-veneers-gurgaon': typeof DentalVeneersGurgaonRoute
  '/dentures': typeof DenturesRoute
  '/faqs': typeof FaqsRoute
  '/full-mouth-dental-implant-treatment-clinic': typeof FullMouthDentalImplantTreatmentClinicRoute
  '/gallery': typeof GalleryRoute
  '/international-patients': typeof InternationalPatientsRoute
  '/invisalign-aligners-golf-course-road': typeof InvisalignAlignersGolfCourseRoadRoute
  '/invisalign-aligners-panchsheel-park': typeof InvisalignAlignersPanchsheelParkRoute
  '/invisalign-clear-aligners-teeth-straightening': typeof InvisalignClearAlignersTeethStraighteningRoute
  '/invisalign-treatment-in-delhi-ncr': typeof InvisalignTreatmentInDelhiNcrRoute
  '/kids-dentistry': typeof KidsDentistryRoute
  '/laser-dentistry': typeof LaserDentistryRoute
  '/painless-extractions-tooth-removal': typeof PainlessExtractionsToothRemovalRoute
  '/painless-root-canal-treatment': typeof PainlessRootCanalTreatmentRoute
  '/painless-wisdom-tooth-extraction': typeof PainlessWisdomToothExtractionRoute
  '/porcelain-crowns': typeof PorcelainCrownsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/regular-dental-checkups': typeof RegularDentalCheckupsRoute
  '/smile-makeovers': typeof SmileMakeoversRoute
  '/teeth-whitening': typeof TeethWhiteningRoute
  '/testimonials': typeof TestimonialsRoute
  '/thank-you': typeof ThankYouRoute
  '/tooth-coloured-restoration': typeof ToothColouredRestorationRoute
  '/veneers': typeof VeneersRoute
  '/why-visit-the-dentist': typeof WhyVisitTheDentistRoute
  '/blog/$blog_slug': typeof BlogBlog_slugRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/best-dental-implant-clinic-panchsheel-park': typeof BestDentalImplantClinicPanchsheelParkRoute
  '/best-smile-makeover-clinic': typeof BestSmileMakeoverClinicRoute
  '/braces': typeof BracesRoute
  '/career': typeof CareerRoute
  '/contact-us': typeof ContactUsRoute
  '/dental-bridges': typeof DentalBridgesRoute
  '/dental-implant-clinic-golf-course-road': typeof DentalImplantClinicGolfCourseRoadRoute
  '/dental-implants-delhi': typeof DentalImplantsDelhiRoute
  '/dental-implants-in-gurgaon': typeof DentalImplantsInGurgaonRoute
  '/dental-rct-delhi': typeof DentalRctDelhiRoute
  '/dental-rct-gurgaon': typeof DentalRctGurgaonRoute
  '/dental-tourism': typeof DentalTourismRoute
  '/dental-veneers-delhi': typeof DentalVeneersDelhiRoute
  '/dental-veneers-gurgaon': typeof DentalVeneersGurgaonRoute
  '/dentures': typeof DenturesRoute
  '/faqs': typeof FaqsRoute
  '/full-mouth-dental-implant-treatment-clinic': typeof FullMouthDentalImplantTreatmentClinicRoute
  '/gallery': typeof GalleryRoute
  '/international-patients': typeof InternationalPatientsRoute
  '/invisalign-aligners-golf-course-road': typeof InvisalignAlignersGolfCourseRoadRoute
  '/invisalign-aligners-panchsheel-park': typeof InvisalignAlignersPanchsheelParkRoute
  '/invisalign-clear-aligners-teeth-straightening': typeof InvisalignClearAlignersTeethStraighteningRoute
  '/invisalign-treatment-in-delhi-ncr': typeof InvisalignTreatmentInDelhiNcrRoute
  '/kids-dentistry': typeof KidsDentistryRoute
  '/laser-dentistry': typeof LaserDentistryRoute
  '/painless-extractions-tooth-removal': typeof PainlessExtractionsToothRemovalRoute
  '/painless-root-canal-treatment': typeof PainlessRootCanalTreatmentRoute
  '/painless-wisdom-tooth-extraction': typeof PainlessWisdomToothExtractionRoute
  '/porcelain-crowns': typeof PorcelainCrownsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/regular-dental-checkups': typeof RegularDentalCheckupsRoute
  '/smile-makeovers': typeof SmileMakeoversRoute
  '/teeth-whitening': typeof TeethWhiteningRoute
  '/testimonials': typeof TestimonialsRoute
  '/thank-you': typeof ThankYouRoute
  '/tooth-coloured-restoration': typeof ToothColouredRestorationRoute
  '/veneers': typeof VeneersRoute
  '/why-visit-the-dentist': typeof WhyVisitTheDentistRoute
  '/blog/$blog_slug': typeof BlogBlog_slugRoute
  '/blog': typeof BlogIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/best-dental-implant-clinic-panchsheel-park': typeof BestDentalImplantClinicPanchsheelParkRoute
  '/best-smile-makeover-clinic': typeof BestSmileMakeoverClinicRoute
  '/braces': typeof BracesRoute
  '/career': typeof CareerRoute
  '/contact-us': typeof ContactUsRoute
  '/dental-bridges': typeof DentalBridgesRoute
  '/dental-implant-clinic-golf-course-road': typeof DentalImplantClinicGolfCourseRoadRoute
  '/dental-implants-delhi': typeof DentalImplantsDelhiRoute
  '/dental-implants-in-gurgaon': typeof DentalImplantsInGurgaonRoute
  '/dental-rct-delhi': typeof DentalRctDelhiRoute
  '/dental-rct-gurgaon': typeof DentalRctGurgaonRoute
  '/dental-tourism': typeof DentalTourismRoute
  '/dental-veneers-delhi': typeof DentalVeneersDelhiRoute
  '/dental-veneers-gurgaon': typeof DentalVeneersGurgaonRoute
  '/dentures': typeof DenturesRoute
  '/faqs': typeof FaqsRoute
  '/full-mouth-dental-implant-treatment-clinic': typeof FullMouthDentalImplantTreatmentClinicRoute
  '/gallery': typeof GalleryRoute
  '/international-patients': typeof InternationalPatientsRoute
  '/invisalign-aligners-golf-course-road': typeof InvisalignAlignersGolfCourseRoadRoute
  '/invisalign-aligners-panchsheel-park': typeof InvisalignAlignersPanchsheelParkRoute
  '/invisalign-clear-aligners-teeth-straightening': typeof InvisalignClearAlignersTeethStraighteningRoute
  '/invisalign-treatment-in-delhi-ncr': typeof InvisalignTreatmentInDelhiNcrRoute
  '/kids-dentistry': typeof KidsDentistryRoute
  '/laser-dentistry': typeof LaserDentistryRoute
  '/painless-extractions-tooth-removal': typeof PainlessExtractionsToothRemovalRoute
  '/painless-root-canal-treatment': typeof PainlessRootCanalTreatmentRoute
  '/painless-wisdom-tooth-extraction': typeof PainlessWisdomToothExtractionRoute
  '/porcelain-crowns': typeof PorcelainCrownsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/regular-dental-checkups': typeof RegularDentalCheckupsRoute
  '/smile-makeovers': typeof SmileMakeoversRoute
  '/teeth-whitening': typeof TeethWhiteningRoute
  '/testimonials': typeof TestimonialsRoute
  '/thank-you': typeof ThankYouRoute
  '/tooth-coloured-restoration': typeof ToothColouredRestorationRoute
  '/veneers': typeof VeneersRoute
  '/why-visit-the-dentist': typeof WhyVisitTheDentistRoute
  '/blog/$blog_slug': typeof BlogBlog_slugRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/best-dental-implant-clinic-panchsheel-park'
    | '/best-smile-makeover-clinic'
    | '/braces'
    | '/career'
    | '/contact-us'
    | '/dental-bridges'
    | '/dental-implant-clinic-golf-course-road'
    | '/dental-implants-delhi'
    | '/dental-implants-in-gurgaon'
    | '/dental-rct-delhi'
    | '/dental-rct-gurgaon'
    | '/dental-tourism'
    | '/dental-veneers-delhi'
    | '/dental-veneers-gurgaon'
    | '/dentures'
    | '/faqs'
    | '/full-mouth-dental-implant-treatment-clinic'
    | '/gallery'
    | '/international-patients'
    | '/invisalign-aligners-golf-course-road'
    | '/invisalign-aligners-panchsheel-park'
    | '/invisalign-clear-aligners-teeth-straightening'
    | '/invisalign-treatment-in-delhi-ncr'
    | '/kids-dentistry'
    | '/laser-dentistry'
    | '/painless-extractions-tooth-removal'
    | '/painless-root-canal-treatment'
    | '/painless-wisdom-tooth-extraction'
    | '/porcelain-crowns'
    | '/privacy-policy'
    | '/regular-dental-checkups'
    | '/smile-makeovers'
    | '/teeth-whitening'
    | '/testimonials'
    | '/thank-you'
    | '/tooth-coloured-restoration'
    | '/veneers'
    | '/why-visit-the-dentist'
    | '/blog/$blog_slug'
    | '/blog/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/best-dental-implant-clinic-panchsheel-park'
    | '/best-smile-makeover-clinic'
    | '/braces'
    | '/career'
    | '/contact-us'
    | '/dental-bridges'
    | '/dental-implant-clinic-golf-course-road'
    | '/dental-implants-delhi'
    | '/dental-implants-in-gurgaon'
    | '/dental-rct-delhi'
    | '/dental-rct-gurgaon'
    | '/dental-tourism'
    | '/dental-veneers-delhi'
    | '/dental-veneers-gurgaon'
    | '/dentures'
    | '/faqs'
    | '/full-mouth-dental-implant-treatment-clinic'
    | '/gallery'
    | '/international-patients'
    | '/invisalign-aligners-golf-course-road'
    | '/invisalign-aligners-panchsheel-park'
    | '/invisalign-clear-aligners-teeth-straightening'
    | '/invisalign-treatment-in-delhi-ncr'
    | '/kids-dentistry'
    | '/laser-dentistry'
    | '/painless-extractions-tooth-removal'
    | '/painless-root-canal-treatment'
    | '/painless-wisdom-tooth-extraction'
    | '/porcelain-crowns'
    | '/privacy-policy'
    | '/regular-dental-checkups'
    | '/smile-makeovers'
    | '/teeth-whitening'
    | '/testimonials'
    | '/thank-you'
    | '/tooth-coloured-restoration'
    | '/veneers'
    | '/why-visit-the-dentist'
    | '/blog/$blog_slug'
    | '/blog'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/best-dental-implant-clinic-panchsheel-park'
    | '/best-smile-makeover-clinic'
    | '/braces'
    | '/career'
    | '/contact-us'
    | '/dental-bridges'
    | '/dental-implant-clinic-golf-course-road'
    | '/dental-implants-delhi'
    | '/dental-implants-in-gurgaon'
    | '/dental-rct-delhi'
    | '/dental-rct-gurgaon'
    | '/dental-tourism'
    | '/dental-veneers-delhi'
    | '/dental-veneers-gurgaon'
    | '/dentures'
    | '/faqs'
    | '/full-mouth-dental-implant-treatment-clinic'
    | '/gallery'
    | '/international-patients'
    | '/invisalign-aligners-golf-course-road'
    | '/invisalign-aligners-panchsheel-park'
    | '/invisalign-clear-aligners-teeth-straightening'
    | '/invisalign-treatment-in-delhi-ncr'
    | '/kids-dentistry'
    | '/laser-dentistry'
    | '/painless-extractions-tooth-removal'
    | '/painless-root-canal-treatment'
    | '/painless-wisdom-tooth-extraction'
    | '/porcelain-crowns'
    | '/privacy-policy'
    | '/regular-dental-checkups'
    | '/smile-makeovers'
    | '/teeth-whitening'
    | '/testimonials'
    | '/thank-you'
    | '/tooth-coloured-restoration'
    | '/veneers'
    | '/why-visit-the-dentist'
    | '/blog/$blog_slug'
    | '/blog/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  BestDentalImplantClinicPanchsheelParkRoute: typeof BestDentalImplantClinicPanchsheelParkRoute
  BestSmileMakeoverClinicRoute: typeof BestSmileMakeoverClinicRoute
  BracesRoute: typeof BracesRoute
  CareerRoute: typeof CareerRoute
  ContactUsRoute: typeof ContactUsRoute
  DentalBridgesRoute: typeof DentalBridgesRoute
  DentalImplantClinicGolfCourseRoadRoute: typeof DentalImplantClinicGolfCourseRoadRoute
  DentalImplantsDelhiRoute: typeof DentalImplantsDelhiRoute
  DentalImplantsInGurgaonRoute: typeof DentalImplantsInGurgaonRoute
  DentalRctDelhiRoute: typeof DentalRctDelhiRoute
  DentalRctGurgaonRoute: typeof DentalRctGurgaonRoute
  DentalTourismRoute: typeof DentalTourismRoute
  DentalVeneersDelhiRoute: typeof DentalVeneersDelhiRoute
  DentalVeneersGurgaonRoute: typeof DentalVeneersGurgaonRoute
  DenturesRoute: typeof DenturesRoute
  FaqsRoute: typeof FaqsRoute
  FullMouthDentalImplantTreatmentClinicRoute: typeof FullMouthDentalImplantTreatmentClinicRoute
  GalleryRoute: typeof GalleryRoute
  InternationalPatientsRoute: typeof InternationalPatientsRoute
  InvisalignAlignersGolfCourseRoadRoute: typeof InvisalignAlignersGolfCourseRoadRoute
  InvisalignAlignersPanchsheelParkRoute: typeof InvisalignAlignersPanchsheelParkRoute
  InvisalignClearAlignersTeethStraighteningRoute: typeof InvisalignClearAlignersTeethStraighteningRoute
  InvisalignTreatmentInDelhiNcrRoute: typeof InvisalignTreatmentInDelhiNcrRoute
  KidsDentistryRoute: typeof KidsDentistryRoute
  LaserDentistryRoute: typeof LaserDentistryRoute
  PainlessExtractionsToothRemovalRoute: typeof PainlessExtractionsToothRemovalRoute
  PainlessRootCanalTreatmentRoute: typeof PainlessRootCanalTreatmentRoute
  PainlessWisdomToothExtractionRoute: typeof PainlessWisdomToothExtractionRoute
  PorcelainCrownsRoute: typeof PorcelainCrownsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RegularDentalCheckupsRoute: typeof RegularDentalCheckupsRoute
  SmileMakeoversRoute: typeof SmileMakeoversRoute
  TeethWhiteningRoute: typeof TeethWhiteningRoute
  TestimonialsRoute: typeof TestimonialsRoute
  ThankYouRoute: typeof ThankYouRoute
  ToothColouredRestorationRoute: typeof ToothColouredRestorationRoute
  VeneersRoute: typeof VeneersRoute
  WhyVisitTheDentistRoute: typeof WhyVisitTheDentistRoute
  BlogBlog_slugRoute: typeof BlogBlog_slugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-visit-the-dentist': {
      id: '/why-visit-the-dentist'
      path: '/why-visit-the-dentist'
      fullPath: '/why-visit-the-dentist'
      preLoaderRoute: typeof WhyVisitTheDentistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veneers': {
      id: '/veneers'
      path: '/veneers'
      fullPath: '/veneers'
      preLoaderRoute: typeof VeneersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tooth-coloured-restoration': {
      id: '/tooth-coloured-restoration'
      path: '/tooth-coloured-restoration'
      fullPath: '/tooth-coloured-restoration'
      preLoaderRoute: typeof ToothColouredRestorationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teeth-whitening': {
      id: '/teeth-whitening'
      path: '/teeth-whitening'
      fullPath: '/teeth-whitening'
      preLoaderRoute: typeof TeethWhiteningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smile-makeovers': {
      id: '/smile-makeovers'
      path: '/smile-makeovers'
      fullPath: '/smile-makeovers'
      preLoaderRoute: typeof SmileMakeoversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regular-dental-checkups': {
      id: '/regular-dental-checkups'
      path: '/regular-dental-checkups'
      fullPath: '/regular-dental-checkups'
      preLoaderRoute: typeof RegularDentalCheckupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/porcelain-crowns': {
      id: '/porcelain-crowns'
      path: '/porcelain-crowns'
      fullPath: '/porcelain-crowns'
      preLoaderRoute: typeof PorcelainCrownsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painless-wisdom-tooth-extraction': {
      id: '/painless-wisdom-tooth-extraction'
      path: '/painless-wisdom-tooth-extraction'
      fullPath: '/painless-wisdom-tooth-extraction'
      preLoaderRoute: typeof PainlessWisdomToothExtractionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painless-root-canal-treatment': {
      id: '/painless-root-canal-treatment'
      path: '/painless-root-canal-treatment'
      fullPath: '/painless-root-canal-treatment'
      preLoaderRoute: typeof PainlessRootCanalTreatmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painless-extractions-tooth-removal': {
      id: '/painless-extractions-tooth-removal'
      path: '/painless-extractions-tooth-removal'
      fullPath: '/painless-extractions-tooth-removal'
      preLoaderRoute: typeof PainlessExtractionsToothRemovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laser-dentistry': {
      id: '/laser-dentistry'
      path: '/laser-dentistry'
      fullPath: '/laser-dentistry'
      preLoaderRoute: typeof LaserDentistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids-dentistry': {
      id: '/kids-dentistry'
      path: '/kids-dentistry'
      fullPath: '/kids-dentistry'
      preLoaderRoute: typeof KidsDentistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invisalign-treatment-in-delhi-ncr': {
      id: '/invisalign-treatment-in-delhi-ncr'
      path: '/invisalign-treatment-in-delhi-ncr'
      fullPath: '/invisalign-treatment-in-delhi-ncr'
      preLoaderRoute: typeof InvisalignTreatmentInDelhiNcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invisalign-clear-aligners-teeth-straightening': {
      id: '/invisalign-clear-aligners-teeth-straightening'
      path: '/invisalign-clear-aligners-teeth-straightening'
      fullPath: '/invisalign-clear-aligners-teeth-straightening'
      preLoaderRoute: typeof InvisalignClearAlignersTeethStraighteningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invisalign-aligners-panchsheel-park': {
      id: '/invisalign-aligners-panchsheel-park'
      path: '/invisalign-aligners-panchsheel-park'
      fullPath: '/invisalign-aligners-panchsheel-park'
      preLoaderRoute: typeof InvisalignAlignersPanchsheelParkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invisalign-aligners-golf-course-road': {
      id: '/invisalign-aligners-golf-course-road'
      path: '/invisalign-aligners-golf-course-road'
      fullPath: '/invisalign-aligners-golf-course-road'
      preLoaderRoute: typeof InvisalignAlignersGolfCourseRoadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/international-patients': {
      id: '/international-patients'
      path: '/international-patients'
      fullPath: '/international-patients'
      preLoaderRoute: typeof InternationalPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/full-mouth-dental-implant-treatment-clinic': {
      id: '/full-mouth-dental-implant-treatment-clinic'
      path: '/full-mouth-dental-implant-treatment-clinic'
      fullPath: '/full-mouth-dental-implant-treatment-clinic'
      preLoaderRoute: typeof FullMouthDentalImplantTreatmentClinicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dentures': {
      id: '/dentures'
      path: '/dentures'
      fullPath: '/dentures'
      preLoaderRoute: typeof DenturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-veneers-gurgaon': {
      id: '/dental-veneers-gurgaon'
      path: '/dental-veneers-gurgaon'
      fullPath: '/dental-veneers-gurgaon'
      preLoaderRoute: typeof DentalVeneersGurgaonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-veneers-delhi': {
      id: '/dental-veneers-delhi'
      path: '/dental-veneers-delhi'
      fullPath: '/dental-veneers-delhi'
      preLoaderRoute: typeof DentalVeneersDelhiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-tourism': {
      id: '/dental-tourism'
      path: '/dental-tourism'
      fullPath: '/dental-tourism'
      preLoaderRoute: typeof DentalTourismRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-rct-gurgaon': {
      id: '/dental-rct-gurgaon'
      path: '/dental-rct-gurgaon'
      fullPath: '/dental-rct-gurgaon'
      preLoaderRoute: typeof DentalRctGurgaonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-rct-delhi': {
      id: '/dental-rct-delhi'
      path: '/dental-rct-delhi'
      fullPath: '/dental-rct-delhi'
      preLoaderRoute: typeof DentalRctDelhiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implants-in-gurgaon': {
      id: '/dental-implants-in-gurgaon'
      path: '/dental-implants-in-gurgaon'
      fullPath: '/dental-implants-in-gurgaon'
      preLoaderRoute: typeof DentalImplantsInGurgaonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implants-delhi': {
      id: '/dental-implants-delhi'
      path: '/dental-implants-delhi'
      fullPath: '/dental-implants-delhi'
      preLoaderRoute: typeof DentalImplantsDelhiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-implant-clinic-golf-course-road': {
      id: '/dental-implant-clinic-golf-course-road'
      path: '/dental-implant-clinic-golf-course-road'
      fullPath: '/dental-implant-clinic-golf-course-road'
      preLoaderRoute: typeof DentalImplantClinicGolfCourseRoadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-bridges': {
      id: '/dental-bridges'
      path: '/dental-bridges'
      fullPath: '/dental-bridges'
      preLoaderRoute: typeof DentalBridgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/braces': {
      id: '/braces'
      path: '/braces'
      fullPath: '/braces'
      preLoaderRoute: typeof BracesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-smile-makeover-clinic': {
      id: '/best-smile-makeover-clinic'
      path: '/best-smile-makeover-clinic'
      fullPath: '/best-smile-makeover-clinic'
      preLoaderRoute: typeof BestSmileMakeoverClinicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-dental-implant-clinic-panchsheel-park': {
      id: '/best-dental-implant-clinic-panchsheel-park'
      path: '/best-dental-implant-clinic-panchsheel-park'
      fullPath: '/best-dental-implant-clinic-panchsheel-park'
      preLoaderRoute: typeof BestDentalImplantClinicPanchsheelParkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$blog_slug': {
      id: '/blog/$blog_slug'
      path: '/blog/$blog_slug'
      fullPath: '/blog/$blog_slug'
      preLoaderRoute: typeof BlogBlog_slugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  BestDentalImplantClinicPanchsheelParkRoute:
    BestDentalImplantClinicPanchsheelParkRoute,
  BestSmileMakeoverClinicRoute: BestSmileMakeoverClinicRoute,
  BracesRoute: BracesRoute,
  CareerRoute: CareerRoute,
  ContactUsRoute: ContactUsRoute,
  DentalBridgesRoute: DentalBridgesRoute,
  DentalImplantClinicGolfCourseRoadRoute:
    DentalImplantClinicGolfCourseRoadRoute,
  DentalImplantsDelhiRoute: DentalImplantsDelhiRoute,
  DentalImplantsInGurgaonRoute: DentalImplantsInGurgaonRoute,
  DentalRctDelhiRoute: DentalRctDelhiRoute,
  DentalRctGurgaonRoute: DentalRctGurgaonRoute,
  DentalTourismRoute: DentalTourismRoute,
  DentalVeneersDelhiRoute: DentalVeneersDelhiRoute,
  DentalVeneersGurgaonRoute: DentalVeneersGurgaonRoute,
  DenturesRoute: DenturesRoute,
  FaqsRoute: FaqsRoute,
  FullMouthDentalImplantTreatmentClinicRoute:
    FullMouthDentalImplantTreatmentClinicRoute,
  GalleryRoute: GalleryRoute,
  InternationalPatientsRoute: InternationalPatientsRoute,
  InvisalignAlignersGolfCourseRoadRoute: InvisalignAlignersGolfCourseRoadRoute,
  InvisalignAlignersPanchsheelParkRoute: InvisalignAlignersPanchsheelParkRoute,
  InvisalignClearAlignersTeethStraighteningRoute:
    InvisalignClearAlignersTeethStraighteningRoute,
  InvisalignTreatmentInDelhiNcrRoute: InvisalignTreatmentInDelhiNcrRoute,
  KidsDentistryRoute: KidsDentistryRoute,
  LaserDentistryRoute: LaserDentistryRoute,
  PainlessExtractionsToothRemovalRoute: PainlessExtractionsToothRemovalRoute,
  PainlessRootCanalTreatmentRoute: PainlessRootCanalTreatmentRoute,
  PainlessWisdomToothExtractionRoute: PainlessWisdomToothExtractionRoute,
  PorcelainCrownsRoute: PorcelainCrownsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RegularDentalCheckupsRoute: RegularDentalCheckupsRoute,
  SmileMakeoversRoute: SmileMakeoversRoute,
  TeethWhiteningRoute: TeethWhiteningRoute,
  TestimonialsRoute: TestimonialsRoute,
  ThankYouRoute: ThankYouRoute,
  ToothColouredRestorationRoute: ToothColouredRestorationRoute,
  VeneersRoute: VeneersRoute,
  WhyVisitTheDentistRoute: WhyVisitTheDentistRoute,
  BlogBlog_slugRoute: BlogBlog_slugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
